


class Foo {
    new() = other_func()
}

def other_func() {
    # This should raise an exception
    new()
}

def __test_exc() {
    #

    # Of course, calling 'new' directly should raise
    # an error
    assert_raises(RuntimeError, def = new())

    # Calling a function that improperly calls new
    # should raise an error
    assert_raises(RuntimeError, def = other_func())

    # If 'new' is called indirectly, from a constructor,
    # that should also raise
    assert_raises(RuntimeError, def = Foo())
}
